node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def scannerHome = tool name: 'SonarScanner for MSBuild', type: 'hudson.plugins.sonar.MsBuildSQRunnerInstallation'
    withSonarQubeEnv('sonarqube') {
      sh """
        dotnet ${scannerHome}/SonarScanner.MSBuild.dll begin /k:"scan-dotnet"
        dotnet build
        dotnet ${scannerHome}/SonarScanner.MSBuild.dll end
      """
    }
  }
}
