pipeline {
    agent { label 'master' }

    environment {
        SONAR_SCANNER_HOME = tool name: 'sonar-ms-build', type: 'SonarScannerTool'
        PATH = "${env.PATH}:${env.HOME}/.dotnet/tools"
    }

    stages {
        stage('SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/AhmedMahmoudAbuzaidd/graduation-project.git'
            }
        }
        stage('Debug Environment') {
            steps {
                sh 'printenv'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh 'dotnet-sonarscanner begin /k:"scan-dotnet"'
                    // Build your project here
                    // sh 'dotnet build <your-project>'
                    sh 'dotnet-sonarscanner end'
                }
            }
        }
    }
}
